#define ENABLE_RAIN_AMBIENCE 1
#define ENABLE_RAIN_DROPS_FX 1
#define ENABLE_RAIN_DROPS_POSTFX 1
#define ENABLE_RAIN_ENVIRONMENT 1

#define RAIN_INTENSITY_OFF 0
#define RAIN_INTENSITY_LOW 1
#define RAIN_INTENSITY_MED 2
#define RAIN_INTENSITY_HIG 3
#define RAIN_DEFAULT_INTENSITY RAIN_INTENSITY_LOW