@echo off

SET TA_GAME_PATH_PROCESS="%~dp0"
SET TA_LOCAL_ASSET_CACHE_PROCESS="%~dp0share\assetconvert"
SET TA_TOOLS_PATH_PROCESS="%~dp0"

setx TA_GAME_PATH %TA_GAME_PATH_PROCESS%
setx TA_LOCAL_ASSET_CACHE %TA_LOCAL_ASSET_CACHE_PROCESS%
setx TA_TOOLS_PATH %TA_TOOLS_PATH_PROCESS%

reg add HKCU\Environment /f /v TA_GAME_PATH /t REG_SZ /d %TA_GAME_PATH_PROCESS%
reg add HKCU\Environment /f /v TA_LOCAL_ASSET_CACHE /t REG_SZ /d %TA_LOCAL_ASSET_CACHE_PROCESS%
reg add HKCU\Environment /f /v TA_TOOLS_PATH /t REG_SZ /d %TA_TOOLS_PATH_PROCESS%

