@echo off

SET FOLDER=%~dp0

IF %FOLDER:~-1% NEQ \ (SET FOLDER="%FOLDER%\")
SET FOLDER=%FOLDER:"=%

SET TA_GAME_PATH=%FOLDER%
SET TA_LOCAL_ASSET_CACHE=%FOLDER%share\assetconvert\
SET TA_TOOLS_PATH=%FOLDER%

setx TA_GAME_PATH "%TA_GAME_PATH%\"
setx TA_LOCAL_ASSET_CACHE "%TA_LOCAL_ASSET_CACHE%\"
setx TA_TOOLS_PATH "%TA_TOOLS_PATH%\"

"%TA_TOOLS_PATH%"\bin\modlauncher.exe
