#define KILL_HELLROUND_WATCHERS_NOTIFICATION "kill_hellround_watchers"
#define KILL_HELLROUND_BAD_ITERATION_WATCHER_NOTIFICATION "kill_hellround_bad_iteration_watcher"

// Mostly for debug purpose, it disables all spawns during hellround.
#define HRSPAWN_ENABLE_SPAWNS 1

#define HRSPAWN_CELLBREAK_VISIT_ROUND_INTERVAL 5
#define HRSPAWN_CELLBREAK_VISIT_ROUND_QUANTITY 3
#define HRSPAWN_CELLBREAK_SPAWN_INTERVAL 15.00
#define HRSPAWN_CELLBREAK_LAST_KILL_BONUS "full_ammo"

// Scaling delay of spawns of the entities
#define HRSPAWN_MIN_DELAY_ZOMBIE 0.15
#define HRSPAWN_MAX_DELAY_ZOMBIE 1.50
#define HRSPAWN_MIN_DELAY_NAPALM 4.00
#define HRSPAWN_MAX_DELAY_NAPALM 11.50
#define HRSPAWN_MIN_DELAY_DOG 1.00
#define HRSPAWN_MAX_DELAY_DOG 6.00
#define HRSPAWN_MIN_DELAY_FURY 0.50
#define HRSPAWN_MAX_DELAY_FURY 7.50
#define HRSPAWN_MIN_DELAY_WASP 2.50
#define HRSPAWN_MAX_DELAY_WASP 9.50

#define HRSPAWN_PLAYER_NUMBER_FACTOR 0.15
#define HRSPAWN_TIME_BEFORE_MIN_SPAWN_DELAY 150000 // in milliseconds
