#define HRMETEOR_CLIENT_FIELD_DISABLE 0
#define HRMETEOR_CLIENT_FIELD_FALLDOWN 1
#define HRMETEOR_CLIENT_FIELD_FALLDOWN_SKIP 2
#define HRMETEOR_CLIENT_FIELD_TRIGGER 3
#define HRMETEOR_CLIENT_FIELD "toggle_hellround_meteor"

#define HRMETEOR_AMBIANCE_SOUND_1 "hr_meteor_amb_1"
#define HRMETEOR_AMBIANCE_SOUND_2 "hr_meteor_amb_2"

#define HRMETEOR_EARTHQUAKE_INTENSITY 0.30
#define HRMETEOR_IMPACT_EARTHQUAKE_INTENSITY 0.75
#define HRMETEOR_IMPACT_EARTHQUAKE_DURATION 1.00
#define HRMETEOR_EXPLODER_IMPACT_TIMINGS array(4.000, 6.500, 8.500, 13.500, 15.000, 18.000)

#define HRMETEOR_TIME_BEFORE_METEORS 25.0
#define HRMETEOR_EXPLODER_TIME 15.0
#define HRMETEOR_FX_EXPLODER_NAME "hellround_meteor_exploder"
#define HRMETEOR_FALLDOWN_FX_EXPLODER_NAME "hellround_meteor_falldown_exploder"

#define HRMETEOR_SND_RAIN_ON_FIRE "toggle_meteor_rain_on_fire_sound"
#define HRMETEOR_SND_METEOR_SIREN "amb_meteor_siren"
#define HRMETEOR_SND_METEOR_SHAKE "meteor_shake_sound"

#define HRMETEOR_TRIGGER_LOCALIZED "METEOR_ACTIVATE"
#define HRMETEOR_TRIGGER_PRICE_STR "50000"
