#define HRENV_TOGGLE_CLIENT_FIELD "toggle_hellround_environment"

#define HRENV_FOG_INDEX_BLOODY 3
#define HRENV_FOG_INDEX_TRANSITION 2
#define HRENV_FOG_INDEX_NORMAL 0
#define HRENV_FOG_RADIANT_TIME 1.00
#define HRENV_FOG_TRANSITION_TIME 3.00

#define HRENV_LIGHTSTATE_INDEX_BLOODY 3
#define HRENV_LIGHTSTATE_INDEX_NORMAL 0
