#define WEATHER_DEBUG 0
#define WEATHER_PRINT_DEBUG(__str) if (WEATHER_DEBUG) IPrintLnBold(__str)

#define WEATHER_INTENSITY_OFF 0
#define WEATHER_INTENSITY_LOW 1
#define WEATHER_INTENSITY_MED 2
#define WEATHER_INTENSITY_HIG 3
